export const projects = [
  {
    slug: "sme-operations-crm",
    status: "Implemented in local development; production rollout not verified.",
    title: "SME Operations CRM",
    category: "Flagship / Full-stack CRM & automation platform",
    description: "A business operations platform connecting customer relationships, sales pipelines, and automation for small businesses.",
    stack: "Next.js · TypeScript · NestJS · PostgreSQL · Prisma · Docker · n8n",
    features: "Lead management; contacts and companies; opportunity pipelines; proposals; projects and onboarding; authentication, roles and permissions; dashboard analytics; tasks and activity tracking; n8n integrations; reliable event/outbox processing; API health monitoring.",
    flowTitle: "Architecture overview",
    flow: ["Next.js interface", "NestJS API + authentication", "Prisma + PostgreSQL", "Event / outbox processing", "n8n automation"],
  },
  {
    slug: "dentalflow",
    status: "Demonstrated prototype; screenshots reviewed, workflow source and end-to-end behavior not yet verified.",
    title: "DentalFlow",
    category: "Clinic appointment automation / Prototype",
    description: "A clinic appointment automation prototype for coordinating patient requests, receptionist approval, scheduling, and follow-up communication.",
    stack: "n8n · Google Calendar · Google Sheets · Gmail / Email · Webhooks · JavaScript",
    features: "Screenshots demonstrate a patient booking form, receptionist approval dashboard, sent confirmation email, and an n8n intake workflow with validation and duplicate-check branches. The workflow collection includes slot pre-checks, alternative slots, reminders, cancellation, and rescheduling. Their execution behavior and lead follow-up automation still need source review.",
    flowTitle: "Appointment workflow overview",
    flow: ["Patient booking request", "Availability check", "Receptionist approval", "Google Calendar", "Confirmation", "Reminder", "Cancellation / reschedule"],
  },
  {
    slug: "landvault",
    status: "Academic prototype using synthetic demonstration data.",
    title: "LandVault",
    category: "Blockchain-secured land registry",
    description: "A land registry connecting cadastral surveys and mapped parcel polygons to title issuance, ownership transfers, and record verification.",
    stack: "Next.js · Supabase · PostgreSQL / PostGIS · GIS · Blockchain · Smart contracts",
    features: "Citizens view properties, ownership and verified records, and track applications. Surveyors draw parcel geometries, submit cadastral surveys, and upload survey information. Government administrators review surveys, register parcels, issue titles, approve transfers, and anchor registry records to blockchain. Includes document generation.",
    flowTitle: "Registry lifecycle",
    flow: ["Survey geometry", "Parcel registration", "Title issuance", "Ownership transfer", "Blockchain anchoring", "Record verification"],
  },
  {
    slug: "cozy-pantry",
    status: "Implemented locally; native-device acceptance remains outstanding.",
    title: "Cozy Pantry",
    category: "Offline-first recipe & meal planning app",
    description: "A mobile application bringing recipe discovery, a personal cookbook, shared cookbook organization, and meal planning together with offline support.",
    stack: "React Native · Expo · TypeScript · SQLite · Supabase",
    features: "Recipe discovery and imports; personal cookbook; shared Pantry spaces and recipe ingredients; meal planning; cooking mode; shared recipes; categories and tags; notifications; offline support and cloud synchronization.",
    flowTitle: "Data architecture overview",
    flow: ["React Native + Expo", "Local SQLite storage", "Cloud synchronization", "Supabase"],
  },
  {
    slug: "april-rose-alpha",
    status: "Source reviewed; live-site contact delivery not tested.",
    title: "April Rose Alpha Portfolio",
    category: "Personal branding / Virtual assistant website",
    description: "A personal portfolio website presenting April Rose Alpha's virtual assistance services, professional experience, and creative work to prospective clients.",
    stack: "Next.js · React · TypeScript · Tailwind CSS · Motion · Resend · Vercel",
    features: "Website development and personal branding; responsive layouts and mobile navigation; service presentation; categorized portfolio gallery and image lightbox; motion effects; contact form with a Resend email integration. Creative work displayed in the gallery belongs to April Rose Alpha.",
    flowTitle: "Visitor journey",
    flow: ["Introduction", "Experience + services", "Creative portfolio", "Contact inquiry"],
    liveUrl: "https://april-rose-alpha-portfolio.vercel.app/",
  },
];
