export const projects = [
  {
    title: "SME Operations CRM",
    category: "Flagship / Full-stack CRM & automation platform",
    description: "A business operations platform connecting customer relationships, sales pipelines, and automation for small businesses.",
    stack: "Next.js · TypeScript · NestJS · PostgreSQL · Prisma · Docker · n8n",
    features: "Lead management; contacts and companies; opportunity pipelines; proposals; projects and onboarding; authentication, roles and permissions; dashboard analytics; tasks and activity tracking; n8n integrations; reliable event/outbox processing; API health monitoring.",
    flowTitle: "Architecture overview",
    flow: ["Next.js interface", "NestJS API + authentication", "Prisma + PostgreSQL", "Event / outbox processing", "n8n automation"],
  },
  {
    title: "DentalFlow",
    category: "Clinic appointment automation",
    description: "An appointment automation system coordinating patient requests, receptionist approval, scheduling, and follow-up communication.",
    stack: "n8n · Google Calendar · Google Sheets · Gmail / Email · Webhooks · JavaScript",
    features: "Availability checks and alternative slots; duplicate booking prevention; receptionist dashboard and approval; lead capture and follow-up; confirmations, reminders, cancellations, and rescheduling.",
    flowTitle: "Appointment workflow",
    flow: ["Patient booking request", "Availability check", "Receptionist approval", "Google Calendar", "Confirmation", "Reminder", "Cancellation / reschedule"],
  },
  {
    title: "LandVault",
    category: "Blockchain-secured land registry",
    description: "A land registry connecting cadastral surveys and mapped parcel polygons to title issuance, ownership transfers, and record verification.",
    stack: "Next.js · Supabase · PostgreSQL / PostGIS · GIS · Blockchain · Smart contracts",
    features: "Citizens view properties, ownership and verified records, and track applications. Surveyors draw parcel geometries, submit cadastral surveys, and upload survey information. Government administrators review surveys, register parcels, issue titles, approve transfers, and anchor registry records to blockchain. Includes document generation.",
    flowTitle: "Registry lifecycle",
    flow: ["Survey geometry", "Parcel registration", "Title issuance", "Ownership transfer", "Blockchain anchoring", "Record verification"],
  },
  {
    title: "Cozy Pantry",
    category: "Offline-first recipe & meal planning app",
    description: "A mobile application bringing recipe discovery, a personal cookbook, pantry management, and meal planning together with offline support.",
    stack: "React Native · Expo · TypeScript · SQLite · Supabase",
    features: "Recipe discovery and imports; personal cookbook; pantry and ingredients; meal planning; cooking mode; shared recipes; categories and tags; notifications; offline support and cloud synchronization.",
    flowTitle: "Data architecture overview",
    flow: ["React Native + Expo", "Local SQLite storage", "Cloud synchronization", "Supabase"],
  },
  {
    title: "Odysseus",
    category: "Experimental / Local AI desktop assistant",
    description: "An experimental Windows assistant exploring natural-language commands, application discovery, and persistent memory.",
    stack: "Local LLM / Qwen · Codex · Windows · Tool execution",
    features: "Core concept: discover an application's executable, launch it, and remember its location for future commands. Exploring filesystem search, a command registry, local LLM support, AI-generated command plans, permission checks, and application-not-found fallbacks. The architecture below is proposed.",
    flowTitle: "Proposed architecture",
    flow: ["User command", "AI assistant", "Intent router", "Local LLM / Codex + memory", "Permission checks", "Windows / files / apps"],
  },
  {
    title: "Yutori Finance Tracker",
    category: "Personal finance web application",
    description: "A finance tracker for managing multiple accounts, budgets, income, and expenses with financial insights and analytics.",
    stack: "Next.js · TypeScript · Prisma · MongoDB",
    features: "Multiple bank accounts; budget management; income and expense tracking; financial insights and analytics. Demonstrates dashboard design, database modeling, and CRUD operations.",
    flowTitle: "Finance overview",
    flow: ["Accounts", "Income + expenses", "Budgets", "Financial analytics"],
  },
  {
    title: "April Rose Alpha Portfolio",
    category: "Personal branding / Virtual assistant website",
    description: "A personal portfolio website presenting April Rose Alpha's virtual assistance services, professional experience, and creative work to prospective clients.",
    stack: "Next.js · React · TypeScript · Tailwind CSS · Motion · Resend · Vercel",
    features: "Website development and personal branding; responsive layouts and mobile navigation; service presentation; categorized portfolio gallery and image lightbox; motion effects; contact form with a Resend email integration. Creative work displayed in the gallery belongs to April Rose Alpha.",
    flowTitle: "Visitor journey",
    flow: ["Introduction", "Experience + services", "Creative portfolio", "Contact inquiry"],
    liveUrl: "https://april-rose-alpha-portfolio.vercel.app/",
  },
];
